### ISSUE TITLE
subprocess.py   raise child_exception OSError: [Errno 2] No such file or directory

### ISSUE THREAD

**Issue by dvska** [niklasb/dryscrape#15]
[Ubuntu 12.10 64bit, Py2.6, Py2.7]

pip install -e git+https://github.com/niklasb/dryscrape.git#egg=dryscrape
pip install -e git+https://github.com/niklasb/webkit-server.git#egg=webkit-server

        ```Python 2.6.7 (r267:88850, Aug 11 2011, 12:18:09) 
        Type "copyright", "credits" or "license" for more information.
        
        IPython 0.13.1 -- An enhanced Interactive Python.
        ?         -> Introduction and overview of IPython's features.
        %quickref -> Quick reference.
        help      -> Python's own help system.
        object?   -> Details about 'object', use 'object??' for extra details.
        
        In [1]: import dryscrape
        
        In [2]: sess = dryscrape.Session(base_url = 'https://google.com')
        ---------------------------------------------------------------------------
        OSError                                   Traceback (most recent call last)
        <ipython-input-2-3781bbfdb247> in <module>()
        ----> 1 sess = dryscrape.Session(base_url = 'https://google.com')
        
        /home/dvs/dev/ENV/src/dryscrape/dryscrape/session.pyc in __init__(self, driver, base_url)
             16                driver = None,
             17                base_url = None):
        ---> 18     self.driver = driver or DefaultDriver()
             19     self.base_url = base_url
             20 
        
        /home/dvs/dev/ENV/src/dryscrape/dryscrape/driver/webkit.pyc in __init__(self, **kw)
             28   def __init__(self, **kw):
             29     kw.setdefault('node_factory_class', NodeFactory)
        ---> 30     super(Driver, self).__init__(**kw)
        
        /home/dvs/dev/ENV/src/webkit-server/webkit_server.pyc in __init__(self, connection, node_factory_class)
            204                node_factory_class = NodeFactory):
            205     super(Client, self).__init__()
        --> 206     self.conn = connection or ServerConnection()
            207     self._node_factory = node_factory_class(self)
            208 
        
        /home/dvs/dev/ENV/src/webkit-server/webkit_server.pyc in __init__(self, server)
            416   def __init__(self, server = None):
            417     super(ServerConnection, self).__init__()
        --> 418     self._sock = (server or get_default_server()).connect()
            419 
            420   def issue_command(self, cmd, *args):
        
        /home/dvs/dev/ENV/src/webkit-server/webkit_server.pyc in get_default_server()
            395   global default_server
            396   if not default_server:
        --> 397     default_server = Server()
            398   return default_server
            399 
        
        /home/dvs/dev/ENV/src/webkit-server/webkit_server.pyc in __init__(self, binary)
            368                                     stdin  = subprocess.PIPE,
            369                                     stdout = subprocess.PIPE,
        --> 370                                     stderr = subprocess.PIPE)
            371     output = self._server.stdout.readline()
            372     try:
        
        /usr/lib/python2.6/subprocess.pyc in __init__(self, args, bufsize, executable, stdin, stdout, stderr, preexec_fn, close_fds, shell, cwd, env, universal_newlines, startupinfo, creationflags)
            621                             p2cread, p2cwrite,
            622                             c2pread, c2pwrite,
        --> 623                             errread, errwrite)
            624 
            625         if mswindows:
        
        /usr/lib/python2.6/subprocess.pyc in _execute_child(self, args, executable, preexec_fn, close_fds, cwd, env, universal_newlines, startupinfo, creationflags, shell, p2cread, p2cwrite, c2pread, c2pwrite, errread, errwrite)
           1139                     if fd is not None:
           1140                         os.close(fd)
        -> 1141                 raise child_exception
           1142 
           1143 
        
        OSError: [Errno 2] No such file or directory

**Comment by sxalexander** [comment]
I have run into the same issue on OSX Yosemite:

```
Python 2.7.6 (default, Sep  9 2014, 15:04:36) 
[GCC 4.2.1 Compatible Apple LLVM 6.0 (clang-600.0.39)] on darwin
Type "help", "copyright", "credits" or "license" for more information.
>>> import dryscrape
>>> s = dryscrape.Session(base_url = 'https://google.com')
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/Users/sxalexander/.virtualenvs/ENV/src/dryscrape/dryscrape/session.py", line 18, in __init__
    self.driver = driver or DefaultDriver()
  File "/Users/sxalexander/.virtualenvs/ENV/src/dryscrape/dryscrape/driver/webkit.py", line 30, in __init__
    super(Driver, self).__init__(**kw)
  File "/Users/sxalexander/.virtualenvs/ENV/src/webkit-server/webkit_server.py", line 225, in __init__
    self.conn = connection or ServerConnection()
  File "/Users/sxalexander/.virtualenvs/ENV/src/webkit-server/webkit_server.py", line 444, in __init__
    self._sock = (server or get_default_server()).connect()
  File "/Users/sxalexander/.virtualenvs/ENV/src/webkit-server/webkit_server.py", line 423, in get_default_server
    default_server = Server()
  File "/Users/sxalexander/.virtualenvs/ENV/src/webkit-server/webkit_server.py", line 396, in __init__
    stderr = subprocess.PIPE)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 709, in __init__
    errread, errwrite)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1326, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```

**Comment by andrisp** [comment]
Same issue on CentOS 7 (dryscrape 0.91). webkit-server installed and running via xvfb-run.

    python examples/gmail.py
    Traceback (most recent call last):
      File "examples/gmail.py", line 12, in <module>
        sess = dryscrape.Session(base_url = 'https://mail.google.com/')
      File "/usr/lib/python2.7/site-packages/dryscrape/session.py", line 18, in __init__
        self.driver = driver or DefaultDriver()
      File "/usr/lib/python2.7/site-packages/dryscrape/driver/webkit.py", line 30, in __init__
        super(Driver, self).__init__(**kw)
      File "/usr/lib/python2.7/site-packages/webkit_server-0.9-py2.7.egg/webkit_server.py", line 225, in __init__
        self.conn = connection or ServerConnection()
      File "/usr/lib/python2.7/site-packages/webkit_server-0.9-py2.7.egg/webkit_server.py", line 444, in __init__
        self._sock = (server or get_default_server()).connect()
      File "/usr/lib/python2.7/site-packages/webkit_server-0.9-py2.7.egg/webkit_server.py", line 423, in get_default_server
        default_server = Server()
      File "/usr/lib/python2.7/site-packages/webkit_server-0.9-py2.7.egg/webkit_server.py", line 396, in __init__
        stderr = subprocess.PIPE)
      File "/usr/lib64/python2.7/subprocess.py", line 711, in __init__
    errread, errwrite)
      File "/usr/lib64/python2.7/subprocess.py", line 1308, in _execute_child
        raise child_exception
    OSError: [Errno 2] No such file or directory

Any suggestions on how to diagnose the problem further? Thanks!

**Comment by niklasb** [comment]
Sorry guys, I totally forgot to comment on this earlier. Apparently the webkit-server egg does not install the thing correctly, I have to look into that.

**Comment by niklasb** [comment]
The instructions at https://dryscrape.readthedocs.org/en/latest/installation.html however are up to date and should work fine.

**Comment by jeisson1** [comment]
I got the same:

Python 2.7.10 (default, May 23 2015, 09:40:32) [MSC v.1500 32 bit (Intel)] on win32
Type "copyright", "credits" or "license()" for more information.
>>> import dryscrape
>>> search_keyword = 'dryscrape'
>>> session = dryscrape.Session(base_url = 'http://google.com')

Traceback (most recent call last):
  File "<pyshell#2>", line 1, in <module>
    session = dryscrape.Session(base_url = 'http://google.com')
  File "C:\Python27\lib\site-packages\dryscrape\session.py", line 18, in __init__
    self.driver = driver or DefaultDriver()
  File "C:\Python27\lib\site-packages\dryscrape\driver\webkit.py", line 30, in __init__
    super(Driver, self).__init__(**kw)
  File "c:\users\jcardenas\src\webkit-server\webkit_server.py", line 225, in __init__
    self.conn = connection or ServerConnection()
  File "c:\users\jcardenas\src\webkit-server\webkit_server.py", line 444, in __init__
    self._sock = (server or get_default_server()).connect()
  File "c:\users\jcardenas\src\webkit-server\webkit_server.py", line 423, in get_default_server
    default_server = Server()
  File "c:\users\jcardenas\src\webkit-server\webkit_server.py", line 396, in __init__
    stderr = subprocess.PIPE)
  File "C:\Python27\lib\subprocess.py", line 710, in __init__
    errread, errwrite)
  File "C:\Python27\lib\subprocess.py", line 958, in _execute_child
    startupinfo)
WindowsError: [Error 2] El sistema no puede encontrar el archivo especificado

**Comment by jeisson1** [comment]
and in Python 3.4: 

import urlparse 
ImportError: No module named  'urlparse'

**Comment by niklasb** [comment]
@jeisson1  Neither Windows nor Python 3 is officially supported. However, webkit-server should build on Windows. It's just that the included [setup.py](https://github.com/niklasb/webkit-server/blob/master/setup.py) assumes that GNU make is available. Please let me know if you get it to build, so that I can include the necessary information in the docs.

**Comment by niklasb** [comment]
The easiest way to install dryscrape now should be `pip2 install dryscrape`. The `-e` option still does not work with `webkit-server`, it somehow skips the `build` step, I'm not entirely sure why.

**Comment by niklasb** [comment]
Please reopen if you experience similar errors with the official installation instruction, i.e. `pip install` or the instructions from https://dryscrape.readthedocs.org/en/latest/installation.html

**Comment by adamwlev** [comment]
I have the same problem on OSX 10.9.5. I followed the official installation instruction - using pip.

```
Adams-MacBook-Pro:predictit adamlevin$ python minnesota.py
Traceback (most recent call last):
  File "minnesota.py", line 41, in <module>
    session = dry.Session(base_url='http://google.com')
  File "build/bdist.macosx-10.9-x86_64/egg/dryscrape/session.py", line 22, in __init__
  File "build/bdist.macosx-10.9-x86_64/egg/dryscrape/driver/webkit.py", line 30, in __init__
  File "/usr/local/lib/python2.7/site-packages/webkit_server-1.0-py2.7.egg/webkit_server.py", line 230, in __init__
    self.conn = connection or ServerConnection()
  File "/usr/local/lib/python2.7/site-packages/webkit_server-1.0-py2.7.egg/webkit_server.py", line 507, in __init__
    self._sock = (server or get_default_server()).connect()
  File "/usr/local/lib/python2.7/site-packages/webkit_server-1.0-py2.7.egg/webkit_server.py", line 450, in get_default_server
    _default_server = Server()
  File "/usr/local/lib/python2.7/site-packages/webkit_server-1.0-py2.7.egg/webkit_server.py", line 416, in __init__
    stderr = subprocess.PIPE)
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 710, in __init__
    errread, err write
  File "/usr/local/Cellar/python/2.7.11/Frameworks/Python.framework/Versions/2.7/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory
```)

**Comment by marconoe** [comment]
Hey guys, ive got the same issue! Please help!!!
`192-168-1-3:pleasework64 marconoe$ /usr/bin/xcodebuild
=== BUILD TARGET pleasework64 OF PROJECT pleasework64 WITH THE DEFAULT CONFIGURATION (Release) ===

Check dependencies

Validate build/Release-iphoneos/pleasework64.app
    cd "/Users/marconoe/Desktop/Data Science/xcode/pleasework64"
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/marconoe/anaconda/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/Applications/Postgres.app/Contents/Versions/latest/bin"
    export PRODUCT_TYPE=com.apple.product-type.application
    builtin-validationUtility /Users/marconoe/Desktop/Data\ Science/xcode/pleasework64/build/Release-iphoneos/pleasework64.app -validate-for-store

** BUILD SUCCEEDED **

192-168-1-3:pleasework64 marconoe$ pip install dryscrape
Collecting dryscrape
Requirement already satisfied: lxml in /Users/marconoe/anaconda/lib/python3.5/site-packages (from dryscrape)
Collecting webkit-server>=1.0 (from dryscrape)
  Using cached webkit-server-1.0.tar.gz
Requirement already satisfied: xvfbwrapper in /Users/marconoe/anaconda/lib/python3.5/site-packages (from dryscrape)
Building wheels for collected packages: webkit-server
  Running setup.py bdist_wheel for webkit-server ... error
  Complete output from command /Users/marconoe/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hy/td1knncs33z6qfg54_2tvd340000gn/T/pip-build-m3yr0gpz/webkit-server/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" bdist_wheel -d /var/folders/hy/td1knncs33z6qfg54_2tvd340000gn/T/tmpkb9o0vfypip-wheel- --python-tag cp35:
  running bdist_wheel
  running build
  Project ERROR: Xcode not set up properly. You may need to confirm the license agreement by running /usr/bin/xcodebuild.
  error: [Errno 2] No such file or directory: 'src/webkit_server'
  
  ----------------------------------------
  Failed building wheel for webkit-server
  Running setup.py clean for webkit-server
Failed to build webkit-server
Installing collected packages: webkit-server, dryscrape
  Running setup.py install for webkit-server ... error
    Complete output from command /Users/marconoe/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hy/td1knncs33z6qfg54_2tvd340000gn/T/pip-build-m3yr0gpz/webkit-server/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/hy/td1knncs33z6qfg54_2tvd340000gn/T/pip-zw222bru-record/install-record.txt --single-version-externally-managed --compile:
    running install
    running build
    Project ERROR: Xcode not set up properly. You may need to confirm the license agreement by running /usr/bin/xcodebuild.
    error: [Errno 2] No such file or directory: 'src/webkit_server'
    
    ----------------------------------------
Command "/Users/marconoe/anaconda/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/hy/td1knncs33z6qfg54_2tvd340000gn/T/pip-build-m3yr0gpz/webkit-server/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/hy/td1knncs33z6qfg54_2tvd340000gn/T/pip-zw222bru-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/hy/td1knncs33z6qfg54_2tvd340000gn/T/pip-build-m3yr0gpz/webkit-server/`

**Comment by mincaeuro** [comment]
Hi got the same problem:
`Traceback (most recent call last):
  File "kataster.py", line 5, in <module>
    session = dryscrape.Session()
  File "/usr/local/lib/python2.7/dist-packages/dryscrape/session.py", line 22, in __init__
    self.driver = driver or DefaultDriver()
  File "/usr/local/lib/python2.7/dist-packages/dryscrape/driver/webkit.py", line 30, in __init__
    super(Driver, self).__init__(**kw)
  File "/usr/local/lib/python2.7/dist-packages/webkit_server.py", line 230, in __init__
    self.conn = connection or ServerConnection()
  File "/usr/local/lib/python2.7/dist-packages/webkit_server.py", line 507, in __init__
    self._sock = (server or get_default_server()).connect()
  File "/usr/local/lib/python2.7/dist-packages/webkit_server.py", line 450, in get_default_server
    _default_server = Server()
  File "/usr/local/lib/python2.7/dist-packages/webkit_server.py", line 416, in __init__
    stderr = subprocess.PIPE)
  File "/usr/lib/python2.7/subprocess.py", line 710, in __init__
    errread, errwrite)
  File "/usr/lib/python2.7/subprocess.py", line 1335, in _execute_child
    raise child_exception
OSError: [Errno 2] No such file or directory`
